version: '3'

services:
  web:
    build: .
    ports:
      - "8080:5000"
    volumes:
      - .:/app
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
